service: inertia_template
image: scouillard/inertia_template

# Deploy to these servers.
servers:
  web:
    - 178.156.253.124 # TODO
  # job:
  #   hosts:
  #     - 192.168.0.1
  #   cmd: bin/jobs

proxy:
  ssl: true
  host: demo.couillard.dev # TODO

registry:
  server: ghcr.io
  username: scouillard
  password:
    - KAMAL_REGISTRY_PASSWORD

env:
  clear:
    SOLID_QUEUE_IN_PUMA: true

    DB_HOST: inertia_template-postgres
    POSTGRES_USER: inertia_template
    POSTGRES_DB: inertia_template_production
  secret:
    - RAILS_MASTER_KEY
    - POSTGRES_PASSWORD
    - GOOGLE_CLIENT_ID
    - GOOGLE_CLIENT_SECRET
    - RESEND_API_KEY

aliases:
  console: app exec --interactive --reuse "bin/rails console"
  shell: app exec --interactive --reuse "bash"
  logs: app logs -f
  dbc: app exec --interactive --reuse "bin/rails dbconsole --include-password"

volumes:
  - "inertia_template_storage:/rails/storage"

asset_path: /rails/public/vite

builder:
  arch: amd64

# Use a different ssh user than root
# ssh:
#   user: app

accessories:
  postgres:
    image: postgres:17
    host: 178.156.253.124 # TODO
    port: "127.0.0.1:5432:5432" # Not sure about this?
    env:
      clear:
        POSTGRES_USER: inertia_template
        POSTGRES_DB: inertia_template_production
      secret:
        - POSTGRES_PASSWORD
    directories:
      - data:/var/lib/postgresql/data
